app:
  autoscale: True
  autocentralize: True
atoms:
  C:
    radius: 0.77
    color:
      red: 0.89
      green: 0.82
      blue: 0.4
  H:
    radius: 0.32
    color:
      red: 0.75
      green: 0.75
      blue: 0.75
  O:
    radius: 0.73
    color:
      red: 0
      green: 0
      blue: 0.1
  S:
    radius: 1.02
    color:
      red: 1
      green: 1
      blue: 0
  N:
    radius: 0.75
    color:
      red: 0
      green: 1
      blue: 0
bonds:
